#ifndef CFBROBOTCONTROLLER_GLOBAL_H
#define CFBROBOTCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CFBROBOTCONTROLLER_EXPORTS
#define CFBROBOTCONTROLLER_API Q_DECL_EXPORT
#else
#define CFBROBOTCONTROLLER_API Q_DECL_IMPORT
#endif

#endif // CFBROBOT3DVIEW_GLOBAL_H
