#ifndef CFBEVENTEDITOR_GLOBAL_H
#define CFBEVENTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFBEVENTEDITOR_LIBRARY)
#  define CFBEVENTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFBEVENTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFBEVENTEDITOR_GLOBAL_H
