#ifndef CFBSOCKETSESSION_GLOBAL_H
#define CFBSOCKETSESSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFBSOCKETSESSION_LIBRARY)
#  define CFBSOCKETSESSIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFBSOCKETSESSIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFBSOCKETSESSION_GLOBAL_H
