#ifndef CFBUPDATEMODULE_GLOBAL_H
#define CFBUPDATEMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFBUPDATEMODULE_LIBRARY)
#  define CFBUPDATEMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFBUPDATEMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFBUPDATEMODULE_GLOBAL_H
