#ifndef CFBROBOT3DVIEW_GLOBAL_H
#define CFBROBOT3DVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFBROBOT3DVIEW_LIBRARY)
#  define CFBROBOT3DVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFBROBOT3DVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFBROBOT3DVIEW_GLOBAL_H
